In [8]:
from sklearn.ensemble import GradientBoostingRegressor as GBR

import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv("train.csv",encoding="shift-jis")
df

index  age workclass  fnlwgt     education  education-num  \
0        322   21   Private  132652  Some-college             10   
1      11968   29   Private  132652       HS-grad              9   
2      10868   19   Private  132652     Bachelors             13   
3       3394   17   Private  132652       HS-grad              9   
4      15993   47   Private  132652  Some-college             10   
...      ...  ...       ...     ...           ...            ...   
11895   9225   23   Private  132652       HS-grad              9   
11896  13123   31   Private  132652       HS-grad              9   
11897   9845   21   Private  132652       HS-grad              9   
11898  10799   29   Private  132652     Bachelors             13   
11899   2732   17   Private  132652       HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0                Divorced       Adm-clerical      Own-child  White  Female   
1                Divorced       Adm-clerical  Not-in-family  White  Female   
2           Never-married     Prof-specialty  Not-in-family  White  Female   
3           Never-married       Craft-repair      Own-child  White    Male   
4      Married-civ-spouse       Craft-repair        Husband  White    Male   
...                   ...                ...            ...    ...     ...   
11895  Married-civ-spouse              Sales           Wife  White  Female   
11896            Divorced      Other-service      Unmarried  Black  Female   
11897       Never-married      Other-service      Own-child  White    Male   
11898       Never-married  Machine-op-inspct  Not-in-family  White    Male   
11899  Married-civ-spouse       Tech-support        Husband  White    Male   

      native-country  Y  
0      United-States  0  
1      United-States  0  
2      United-States  0  
3      United-States  0  
4      United-States  0  
...              ... ..  
11895  United-States  0  
11896  United-States  0  
11897  United-States  0  
11898  United-States  0  
11899  United-States  1  

[11900 rows x 13 columns]

In [10]:
df=df.drop(["index","fnlwgt"],axis=1)

In [11]:
df

age workclass     education  education-num      marital-status  \
0       21   Private  Some-college             10            Divorced   
1       29   Private       HS-grad              9            Divorced   
2       19   Private     Bachelors             13       Never-married   
3       17   Private       HS-grad              9       Never-married   
4       47   Private  Some-college             10  Married-civ-spouse   
...    ...       ...           ...            ...                 ...   
11895   23   Private       HS-grad              9  Married-civ-spouse   
11896   31   Private       HS-grad              9            Divorced   
11897   21   Private       HS-grad              9       Never-married   
11898   29   Private     Bachelors             13       Never-married   
11899   17   Private       HS-grad              9  Married-civ-spouse   

              occupation   relationship   race     sex native-country  Y  
0           Adm-clerical      Own-child  White  Female  United-States  0  
1           Adm-clerical  Not-in-family  White  Female  United-States  0  
2         Prof-specialty  Not-in-family  White  Female  United-States  0  
3           Craft-repair      Own-child  White    Male  United-States  0  
4           Craft-repair        Husband  White    Male  United-States  0  
...                  ...            ...    ...     ...            ... ..  
11895              Sales           Wife  White  Female  United-States  0  
11896      Other-service      Unmarried  Black  Female  United-States  0  
11897      Other-service      Own-child  White    Male  United-States  0  
11898  Machine-op-inspct  Not-in-family  White    Male  United-States  0  
11899       Tech-support        Husband  White    Male  United-States  1  

[11900 rows x 11 columns]

In [12]:
model=GBR(n_estimators=10)

In [15]:
df=pd.get_dummies(df,columns=["workclass","education","marital-status","occupation","relationship","race","sex","native-country"])

In [16]:
df

age  education-num  Y  workclass_?  workclass_Federal-gov  \
0       21             10  0            0                      0   
1       29              9  0            0                      0   
2       19             13  0            0                      0   
3       17              9  0            0                      0   
4       47             10  0            0                      0   
...    ...            ... ..          ...                    ...   
11895   23              9  0            0                      0   
11896   31              9  0            0                      0   
11897   21              9  0            0                      0   
11898   29             13  0            0                      0   
11899   17              9  1            0                      0   

       workclass_Local-gov  workclass_Private  workclass_Self-emp-inc  \
0                        0                  1                       0   
1                        0                  1                       0   
2                        0                  1                       0   
3                        0                  1                       0   
4                        0                  1                       0   
...                    ...                ...                     ...   
11895                    0                  1                       0   
11896                    0                  1                       0   
11897                    0                  1                       0   
11898                    0                  1                       0   
11899                    0                  1                       0   

       workclass_Self-emp-not-inc  workclass_State-gov  ...  \
0                               0                    0  ...   
1                               0                    0  ...   
2                               0                    0  ...   
3                               0                    0  ...   
4                               0                    0  ...   
...                           ...                  ...  ...   
11895                           0                    0  ...   
11896                           0                    0  ...   
11897                           0                    0  ...   
11898                           0                    0  ...   
11899                           0                    0  ...   

       relationship_Unmarried  relationship_Wife  race_Asian-Pac-Islander  \
0                           0                  0                        0   
1                           0                  0                        0   
2                           0                  0                        0   
3                           0                  0                        0   
4                           0                  0                        0   
...                       ...                ...                      ...   
11895                       0                  1                        0   
11896                       1                  0                        0   
11897                       0                  0                        0   
11898                       0                  0                        0   
11899                       0                  0                        0   

       race_Black  race_White  sex_Female  sex_Male  native-country_Mexico  \
0               0           1           1         0                      0   
1               0           1           1         0                      0   
2               0           1           1         0                      0   
3               0           1           0         1                      0   
4               0           1           0         1                      0   
...           ...         ...         ...       ...                    ...   
11895           0           1           1         0                      0   
11896  

In [17]:
y_name="age"
y=df[y_name].values
x_table=df.drop(y_name,axis=1)
x_name=x_table.columns
x=x_table.values

In [18]:
x

array([[10,  0,  0, ...,  0,  0,  1],
       [ 9,  0,  0, ...,  0,  0,  1],
       [13,  0,  0, ...,  0,  0,  1],
       ...,
       [ 9,  0,  0, ...,  0,  0,  1],
       [13,  0,  0, ...,  0,  0,  1],
       [ 9,  1,  0, ...,  0,  0,  1]], dtype=int64)

In [19]:
df.to_csv("newdata.csv",index=False,encoding="shift-jis")

In [20]:
model=GBR(n_estimators=25)

In [21]:
model.fit(x,y)

GradientBoostingRegressor(n_estimators=25)

In [22]:
model.feature_importances_

array([1.70444121e-01, 3.44135337e-01, 6.60354170e-04, 9.92130289e-03,
       1.20566117e-02, 3.15635098e-02, 2.15281642e-02, 9.98759012e-04,
       0.00000000e+00, 0.00000000e+00, 1.27940776e-02, 4.35473444e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.89765283e-04, 0.00000000e+00, 1.23368509e-03, 1.22622051e-02,
       3.94423714e-02, 0.00000000e+00, 1.51824155e-02, 6.34932752e-02,
       1.04324579e-03, 8.49636137e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.68867880e-03, 3.33010570e-03, 2.54966483e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.77830963e-03, 8.41496544e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.19073729e-01, 3.67267755e-03, 4.15213651e-03, 2.54156050e-03,
       1.59547615e-03, 1.99354515e-03, 1.23401587e-03, 1.57986378e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [23]:
import pickle
fname="mode.sav"
pickle.dump(model, open(fname, 'wb'))

In [24]:
model2=pickle.load(open(fname, 'rb'))

In [25]:
model2.feature_importances_

array([1.70444121e-01, 3.44135337e-01, 6.60354170e-04, 9.92130289e-03,
       1.20566117e-02, 3.15635098e-02, 2.15281642e-02, 9.98759012e-04,
       0.00000000e+00, 0.00000000e+00, 1.27940776e-02, 4.35473444e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.89765283e-04, 0.00000000e+00, 1.23368509e-03, 1.22622051e-02,
       3.94423714e-02, 0.00000000e+00, 1.51824155e-02, 6.34932752e-02,
       1.04324579e-03, 8.49636137e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.68867880e-03, 3.33010570e-03, 2.54966483e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.77830963e-03, 8.41496544e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.19073729e-01, 3.67267755e-03, 4.15213651e-03, 2.54156050e-03,
       1.59547615e-03, 1.99354515e-03, 1.23401587e-03, 1.57986378e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [26]:
for i in range(len(x_name)):
    print(x_name[i])

education-num
Y
workclass_?
workclass_Federal-gov
workclass_Local-gov
workclass_Private
workclass_Self-emp-inc
workclass_Self-emp-not-inc
workclass_State-gov
education_10th
education_11th
education_12th
education_1st-4th
education_5th-6th
education_7th-8th
education_9th
education_Assoc-acdm
education_Assoc-voc
education_Bachelors
education_HS-grad
education_Masters
education_Prof-school
education_Some-college
marital-status_Divorced
marital-status_Married-civ-spouse
marital-status_Never-married
marital-status_Separated
marital-status_Widowed
occupation_?
occupation_Adm-clerical
occupation_Craft-repair
occupation_Exec-managerial
occupation_Farming-fishing
occupation_Handlers-cleaners
occupation_Machine-op-inspct
occupation_Other-service
occupation_Prof-specialty
occupation_Protective-serv
occupation_Sales
occupation_Tech-support
occupation_Transport-moving
relationship_Husband
relationship_Not-in-family
relationship_Other-relative
relationship_Own-child
relationship_Unmarried
relationsh

In [32]:
dfo=pd.DataFrame(x)
dfo.columns=x_name
dfo.to_csv("tohtml.csv",index=False,encoding="shift-jis")